### ISSUE TITLE
python widget bugging out with 'python not responding' message

### ISSUE THREAD

**Issue by sagarmk** [frescobaldi/qpageview#10]
Everytime I am using any of qpageview methods, my python qt app basically bugs out with displaying nothing.
I am able to create pyqt5 apps by default so is there any other dependency I am missing out here ?

Using sample code available on https://qpageview.org/

```
import qpageview
from PyQt5.Qt import *
a = QApplication([])

v = qpageview.View()
v.show()
v.loadPdf("path/to/afile.pdf")
```

![image](https://user-images.githubusercontent.com/4992875/123972352-62b4f600-d980-11eb-9d3e-4e2497eea64b.png)

**Comment by wbsoft** [comment]
You should create a Qt eventloop, as with every Qt application, so if not in an interactive Python session add `a.exec()` so the Qt event loop will start and the widget actually can be used
