### ISSUE TITLE
Type problem in shadow.py, crashes frescobaldi on Python 3.10

### ISSUE THREAD

**Issue by limburgher** [frescobaldi/qpageview#11]
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'
QWidget::repaint: Recursive repaint detected

**Comment by wbsoft** [comment]
limburgher: thanks! I looked thoroughly through the issue, and tried to fix all implicit float->int conversions.

**Comment by limburgher** [comment]
Thank you! I fear my patch in Fedora is incomplete; will there be a release soon or should I update my patch?
