### ISSUE TITLE
Please clarify GPL version used for qpageview

### ISSUE THREAD

**Issue by jbfavre** [frescobaldi/qpageview#15]
Hello,
While wokring on packaging `qpageview` for Debian, it has come to my attention that `qpageview` licensing isn't perfectly clear:
* according to [setup.py](https://github.com/frescobaldi/qpageview/blob/master/setup.py#L57), qpageview is licensed under GPL-3+
* according to [some](https://github.com/frescobaldi/qpageview/blob/master/qpageview/cache.py#L9-L10) [other](https://github.com/frescobaldi/qpageview/blob/master/qpageview/document.py#L9-L10) [files](https://github.com/frescobaldi/qpageview/blob/master/qpageview/multipage.py#L9-L10), `gpageview` is licensed under GPL-2+

Please note that current licensing is **not** a blocker for `qpageview` to be added into Debian, actually it has been integrated today, but it's still important to clarify this point to avoid any misunderstanding.

I suggest to update all files to GPL3+ to be consistent with `setup.py`

Best

**Comment by fedelibre** [comment]
@jbfavre We are preparing a new release.

The license version (GPL v3) is now specified in pyproject.toml file, but the project files still have older numbers. Should we update the numbers or just remove the license section at the beginning of each file? What's the current best practice?
