### ISSUE TITLE
PyQt6 port: PDF rendered deformed on zoom > 125%

### ISSUE THREAD

**Issue by igneus** [frescobaldi/qpageview#25]
(related to #24 , not to the current master; first mentioned in https://github.com/frescobaldi/frescobaldi/pull/1780#issuecomment-2298557403 ; all examples are from Frescobaldi, but the issue is probably in qpageview)

From certain zoom level on - I'm not sure any more that there is a single fixed threshold - the PDF is rendered deformed, as if with different horizontal and vertical zoom ratios, so that this

![2024-08-21-122155_1366x768_scrot](https://github.com/user-attachments/assets/3862b39f-c895-48c5-a8bc-d452870e063f)

becomes this

![2024-08-21-122140_1366x768_scrot](https://github.com/user-attachments/assets/d6988aa8-e3bc-4aee-844e-7325824c1cc4)

The magnifier glass always renders deformed (i.e. the deformation doesn't depend on current zoom level of the document).

## "Tile pattern issue"

Another issue with the magnifier glass (possibly related, possibly not) is that it treats the document as an endlessly repeated tile pattern - i.e. on reaching an edge (top of the first page, bottom of the last page, left/right edge of any page) it doesn't render page edge, but continues with contents of the opposite edge.

Example: green arrow points to the magnified document title (top of the first page in the document), red arrow to the tagline (bottom of the last page).

![2024-08-21-123859_1366x768_scrot](https://github.com/user-attachments/assets/ac7c786e-e5b5-438a-aaff-55b7a73d167e)

**Comment by bmjcode** [comment]
The good news is I've found and fixed the immediate problem. Around 125% zoom is where qpageview starts breaking up pages into individually-rendered tiles. That was one of those things I didn't fully understand in the original Poppler code, so as I suspected my own code was handling the tile geometry incorrectly.

The one small catch is my "fix" defeats the entire purpose of tile-based rendering. See, Poppler allows selectively rendering just part of a page, but QtPdf forces us to render the whole thing. My fix mimics Poppler's functionality by cropping the rendered page, which avoids breaking the existing logic. But now we're rendering the entire page for each tile -- exactly what tile-based rendering is meant to avoid -- only to use a small section of it each time.

Does anyone have suggestions for a better long-term fix?

**Comment by jeanas** [comment]
You might search for other apps that use QtPdf and dig into their source code to check what they do about this.

**Comment by bmjcode** [comment]
It turns out the apparent inefficiency of the rendering code is negligible in practice. Rendering in Frescobaldi stays smooth at high zooms even on an ancient Core 2 Duo machine, while memory usage is comparable to v3.3.0 under Qt 5. I may revisit this if I think of something clever, but for now it's not the pressing concern I initially assumed.

**Comment by igneus** [comment]
> It turns out the apparent inefficiency of the rendering code is negligible in practice.

The performance penalty is really heavy for the magnifier glass. On my workstation it's practically unusable. (But the computer is more than a decade old and I don't pretend that the magnifier glass is a key feature for me.)

**Comment by bmjcode** [comment]
Well, let me take another look then. If it's rendering pages sequentially then maybe caching the last rendered page will be enough. I played around with a more extensive cache yesterday but it just blew up memory usage.

**Comment by bmjcode** [comment]
> If it's rendering pages sequentially then maybe caching the last rendered page will be enough.

Nope, that won't work because tile rendering goes back and forth between pages when more than one is visible.

I've created a [`qt6-pdf-render-cache` branch](https://github.com/bmjcode/qpageview/tree/qt6-pdf-render-cache) to experiment with this further. I'm not thrilled with my own attempt because it roughly triples (!) memory usage, but maybe you can come up with something better.
