### ISSUE TITLE
[Question] How to export the pages in a view

### ISSUE THREAD

**Issue by mantielero** [frescobaldi/qpageview#4]
I am trying to use [pdf](https://qpageview.org/export.html?highlight=export#qpageview.export.pdf), but I don't know how to provide the `pageList` from a View.

**Comment by wbsoft** [comment]
For the `export.pdf` function, `pageList` should be a list of Page objects. (The documentation doesn't state this clearly.) You can get the list of all Page objects in a View using `view.pageLayout()[:]`.

I think I should add a `View.pages()` method which is more clear.

**Comment by wbsoft** [comment]
closing, I added ``View.pages()`` and explained the question :-)
