### ISSUE TITLE
qpageview just show a blank window, not a pdf!

### ISSUE THREAD

**Issue by Tecnoll** [frescobaldi/qpageview#8]
### Hello i have a bug!
I am using **python 3.8** 64-bit, windows 10 64-bit, qpageview 0.6, and this is my code:

`
from PyQt5.Qt import *
import sys

import qpageview

app = QApplication([])

v = qpageview.View()
v.show()
v.loadPdf("exercicios.pdf") #file size(74KB)

sys.exit(app.exec_())
`
But it just show a **blank** widget like a QMainwindow!

whats do wrong???

**Comment by wbsoft** [comment]
Did you install python-poppler-qt5 binding?
Try in python:
```
import popplerqt5
```

**Comment by NgJinXiang14** [comment]
> Did you install python-poppler-qt5 binding?
> Try in python:
> 
> ```
> import popplerqt5
> ```
![image](https://user-images.githubusercontent.com/6142827/110193724-a2efe600-7e70-11eb-8a50-12527b2b75c5.png)

Mine is same too, just not working somehow

**Comment by wbsoft** [comment]
Good luck!
