### ISSUE TITLE
Printing Option not Working

### ISSUE THREAD

**Issue by NgJinXiang14** [frescobaldi/qpageview#9]
![image](https://user-images.githubusercontent.com/6142827/110460313-faa87e80-8108-11eb-90ac-b45ffbb8f775.png)
I already try most printing option but all of them are not working, it keep print without option applied, did I do something wrong? Can anyone help me?

**Comment by wbsoft** [comment]
Which object is in `self.conn` ? You call `printFile` but if that is [Handle](https://github.com/frescobaldi/qpageview/blob/39a709118da26ce7a3d06a07067a56ea707c610a/qpageview/cupsprinter.py#L79) than you should give the filename as first argument.

**Comment by NgJinXiang14** [comment]
> Which object is in `self.conn` ? You call `printFile` but if that is [Handle](https://github.com/frescobaldi/qpageview/blob/39a709118da26ce7a3d06a07067a56ea707c610a/qpageview/cupsprinter.py#L79) than you should give the filename as first argument.

self.conn = cups.Connection()
the problem is I can print, it just the option is not working, like that print range

here's my code
https://github.com/NgJinXiang14/PrintBoothSystem/blob/main/Main%20System.py
sry for the mess up coding tho, I just start PyQt5 and Python last week
